### ISSUE TITLE
Popup details

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#4]
A number of layout changes and adjustments are needed for the popup. This includes:

- Add country and show landscape/province fields, if country is Sweden, show only the landscape, else show the land and the locations, remove parentheses around locations (because usage of parenthesis indicates "not found but given" and shouldn't be used unless present in source data)
- Replace NA values with empty strings
- Image of the bird, linked to other resource with more information about the species or its population trends
- The popup text "Märkdatum:" should be "Märkt:" / "Ringed:"
- The popup text "Fyndests datum: " should be "Funnen: " / "Recovered: "
- Add "Fyndets År" and "Fyndets Månad" in the simple UI

**Comment by mskyttner** [comment]
I have tried to follow the above requests for changing the popup details. Please review and comment.

**Comment by thomwenn** [comment]
- Now the popups are much better!
- In English we prefer using "Species" instead of "Vernacular" in both selection fields and popup.
- Countries should be sorted alphabetic.
- In Swedish the months should have Swedish names.
- Impossible to drag use bars with mouse to select species, year etc.
- Remove "Source" field in simple UI. 
- Add info about current selection (perhaps in empty space top right above map) as "Robin - 4000 latest recoveries of 13 456",  or if no species selected "All species - 4000 latest recoveries".
- Perhaps we could have the possibility to add one source code in a special url for use to display the data for one selected ringer/bird observatory. (can wait some time)

**Comment by mskyttner** [comment]
- Status row to indicate what filters are active and if there is a max limit applied to the display results
- See if Source be a field that is filtered from Bookmarkable State in the URL (but not UI)

**Comment by mskyttner** [comment]
Should be fixed in latest version in production now
